
###

POST http://localhost:3000/save/0mwqqb9u0 

{
  "text": "",
  "alignment": "bottom-left",
  "image": {
    "url": "//placehold.it/1080x1080/ccc/222?text=Adicionar+um+URL+ou+fazer+upload+de+imagem",
    "saturation": 1,
    "contrast": 1,
    "brightness": 1,
    "blur": 0
  }
}

###

GET http://localhost:3000/archive
